name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: db_mahasiswa
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: mvn clean install --file pom.xml

    - name: Build package
      run: mvn package

    - name: SonarQube Scan
      run: mvn clean verify sonar:sonar -D"sonar.projectKey=UTSDevOps" -D"sonar.projectName=UTSDevOps" -D"sonar.host.url=https://6fe5-103-233-100-235.ngrok-free.app" -D"sonar.token=sqp_d60ed52b99e0f940fb8860e9089dcfbdb42a53c3"
